version: '3'
services:
  datajoint:
    build: .
    env_file: .env
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/ibl-pipeline
      - ./data:/data
      - /Users/urai/Google Drive/Rig building WG/DataFigures/BehaviourData_Weekly/Snapshot_DataJoint/:/Snapshot_DataJoint_shortcut
    ports:
      - "8888:8888"
