version: '3'
services:
  datajoint:
    build: .
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/alyx-pipeline
    links:
      - db
    ports:
      - "8888:8888"
  db:
    image: datajoint/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=simple
